/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectpaint_v1;

import java.awt.Color;
import javax.swing.*;
import java.awt.Dimension;


public class Paint extends JFrame {

    /**
     * Creates new form Paint
     */
    public Paint() {
        initComponents();
        PaintBoard.jFrameToolkit = getToolkit();
        Dimension size = PaintBoard.jFrameToolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.setCursor(CROSSHAIR_CURSOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPage1 = new PaintBoard();
        grey = new JPanel();
        circleButton = new JButton();
        lineSegmentButton = new JButton();
        squareButton = new JButton();
        rectangleButton = new JButton();
        triangleButton = new JButton();
        undoButton = new JButton();
        colorButton = new JButton();
        jLabel2 = new JLabel();
        redoButton = new JButton();
        clearButton = new JButton();
        resizeButton = new JButton();
        orange = new JButton();
        pink = new JButton();
        labani = new JButton();
        purple = new JButton();
        black = new JButton();
        blue = new JButton();
        red = new JButton();
        green = new JButton();
        yellow = new JButton();
        jButton15 = new JButton();
        screenshotButton = new JButton();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jSeparator1 = new JSeparator();
        jSeparator2 = new JSeparator();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        eraseButton = new JButton();
        paintButton1 = new JButton();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jSeparator3 = new JSeparator();
        jSeparator4 = new JSeparator();
        logoLabel = new JLabel();
        jSeparator5 = new JSeparator();
        thicknessSlider = new JSlider();
        jLabel15 = new JLabel();
        arcButton = new JButton();
        jLabel16 = new JLabel();
        moveButton = new JButton();
        jLabel17 = new JLabel();
        copyButton = new JButton();
        jLabel18 = new JLabel();
        pasteButton = new JButton();
        jLabel19 = new JLabel();
        jSeparator6 = new JSeparator();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(204, 255, 255));

        viewPage1.setBackground(new Color(255, 255, 255));

        GroupLayout viewPage1Layout = new GroupLayout(viewPage1);
        viewPage1.setLayout(viewPage1Layout);
        viewPage1Layout.setHorizontalGroup(
            viewPage1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viewPage1Layout.setVerticalGroup(
            viewPage1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        grey.setBackground(new Color(0, 102, 102));
        grey.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        circleButton.setIcon(new ImageIcon(getClass().getResource("/circle icon.png"))); // NOI18N
        circleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        circleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        circleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleButtonActionPerformed(evt);
            }
        });

        lineSegmentButton.setIcon(new ImageIcon(getClass().getResource("/lineSegment-icon.png"))); // NOI18N
        lineSegmentButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lineSegmentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lineSegmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineSegmentButtonActionPerformed(evt);
            }
        });

        squareButton.setIcon(new ImageIcon(getClass().getResource("/square.png"))); // NOI18N
        squareButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        squareButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        squareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareButtonActionPerformed(evt);
            }
        });

        rectangleButton.setIcon(new ImageIcon(getClass().getResource("/rectangle-icon.png"))); // NOI18N
        rectangleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rectangleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleButtonActionPerformed(evt);
            }
        });

        triangleButton.setIcon(new ImageIcon(getClass().getResource("/triangle.png"))); // NOI18N
        triangleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        triangleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        triangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleButtonActionPerformed(evt);
            }
        });

        undoButton.setIcon(new ImageIcon(getClass().getResource("/undo-6.png"))); // NOI18N
        undoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        undoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        colorButton.setBackground(new Color(0, 0, 0));
        colorButton.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        colorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Color");

        redoButton.setIcon(new ImageIcon(getClass().getResource("/redo-6.png"))); // NOI18N
        redoButton.setActionCommand("redo");
        redoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        redoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoButtonActionPerformed(evt);
            }
        });

        clearButton.setIcon(new ImageIcon(getClass().getResource("/clear-icon.png"))); // NOI18N
        clearButton.setBorder(BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), BorderFactory.createLineBorder(new Color(0, 0, 0))));
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        resizeButton.setIcon(new ImageIcon(getClass().getResource("/resize-icon.png"))); // NOI18N
        resizeButton.setBorder(BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), BorderFactory.createLineBorder(new Color(0, 0, 0))));
        resizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeButtonActionPerformed(evt);
            }
        });

        orange.setBackground(new Color(255, 153, 0));
        orange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActionPerformed(evt);
            }
        });

        pink.setBackground(new Color(255, 204, 255));
        pink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkActionPerformed(evt);
            }
        });

        labani.setBackground(new Color(0, 255, 255));
        labani.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labaniActionPerformed(evt);
            }
        });

        purple.setBackground(new Color(153, 0, 153));
        purple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleActionPerformed(evt);
            }
        });

        black.setBackground(new Color(0, 0, 0));
        black.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackActionPerformed(evt);
            }
        });

        blue.setBackground(new Color(0, 0, 255));
        blue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueActionPerformed(evt);
            }
        });

        red.setBackground(new Color(255, 0, 0));
        red.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });

        green.setBackground(new Color(0, 153, 0));
        green.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });

        yellow.setBackground(new Color(255, 255, 102));
        yellow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowActionPerformed(evt);
            }
        });

        jButton15.setBackground(new Color(102, 102, 102));
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        screenshotButton.setIcon(new ImageIcon(getClass().getResource("/screenshot-icon.png"))); // NOI18N
        screenshotButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        screenshotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        screenshotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenshotButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Redo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("Undo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("Clear");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setText("Resize");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setText("Screenshot");

        jSeparator1.setBackground(new Color(0, 102, 102));
        jSeparator1.setOrientation(SwingConstants.VERTICAL);

        jSeparator2.setBackground(new Color(0, 102, 102));
        jSeparator2.setOrientation(SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setText("Square");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setText("Line");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel9.setText("Triangle");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel10.setText("Circle");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel11.setText("Rectangle");

        eraseButton.setIcon(new ImageIcon(getClass().getResource("/Eraser-icon.png"))); // NOI18N
        eraseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eraseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseButtonActionPerformed(evt);
            }
        });

        paintButton1.setIcon(new ImageIcon(getClass().getResource("/pencil-cursor.png"))); // NOI18N
        paintButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paintButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel12.setText("Paint");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel13.setText("Erase");

        jSeparator3.setBackground(new Color(0, 102, 102));
        jSeparator3.setOrientation(SwingConstants.VERTICAL);

        jSeparator4.setBackground(new Color(0, 102, 102));
        jSeparator4.setForeground(new Color(0, 102, 102));
        jSeparator4.setOrientation(SwingConstants.VERTICAL);
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logoLabel.setHorizontalAlignment(SwingConstants.CENTER);
        logoLabel.setIcon(new ImageIcon(getClass().getResource("/YAMY LOGO.png"))); // NOI18N
        logoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoLabelMouseClicked(evt);
            }
        });

        jSeparator5.setBackground(new Color(0, 102, 102));
        jSeparator5.setOrientation(SwingConstants.VERTICAL);

        thicknessSlider.setMaximum(50);
        thicknessSlider.setMinimum(1);
        thicknessSlider.setValue(1);
        thicknessSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thicknessSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thicknessSliderStateChanged(evt);
            }
        });
        thicknessSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thicknessSliderMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                thicknessSliderMouseReleased(evt);
            }
        });

        jLabel15.setText("Brush Thickness");

        arcButton.setIcon(new ImageIcon(getClass().getResource("/fill-color.png"))); // NOI18N
        arcButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        arcButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel16.setText("Fill");

        moveButton.setIcon(new ImageIcon(getClass().getResource("/move-icon.png"))); // NOI18N
        moveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        moveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel17.setText("Move");

        copyButton.setIcon(new ImageIcon(getClass().getResource("/copy-icon-1.png"))); // NOI18N
        copyButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        copyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel18.setText("Copy");

        pasteButton.setIcon(new ImageIcon(getClass().getResource("/paste-icon-colored.png"))); // NOI18N
        pasteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pasteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButtonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel19.setText("Paste");

        jSeparator6.setBackground(new Color(0, 102, 102));
        jSeparator6.setOrientation(SwingConstants.VERTICAL);

        GroupLayout greyLayout = new GroupLayout(grey);
        grey.setLayout(greyLayout);
        greyLayout.setHorizontalGroup(
            greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(greyLayout.createSequentialGroup()
                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(greyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(greyLayout.createSequentialGroup()
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(colorButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(pink, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(red, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(green, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blue, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(labani, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purple, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(yellow, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton15, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(black, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orange, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)))
                            .addComponent(thicknessSlider, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(greyLayout.createSequentialGroup()
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(eraseButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addComponent(jSeparator1, GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                            .addGroup(greyLayout.createSequentialGroup()
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paintButton1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47))))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel15)))
                .addGap(69, 69, 69)
                .addComponent(logoLabel, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(jSeparator6, GroupLayout.PREFERRED_SIZE, 6, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(greyLayout.createSequentialGroup()
                        .addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel11)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(copyButton, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasteButton, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator5, GroupLayout.PREFERRED_SIZE, 7, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(greyLayout.createSequentialGroup()
                                .addComponent(rectangleButton, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(circleButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                            .addGroup(greyLayout.createSequentialGroup()
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel16, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(arcButton, GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(greyLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(triangleButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GroupLayout.Alignment.TRAILING, greyLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(GroupLayout.Alignment.TRAILING, greyLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(squareButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lineSegmentButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(greyLayout.createSequentialGroup()
                        .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(moveButton)
                            .addComponent(screenshotButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(greyLayout.createSequentialGroup()
                        .addComponent(undoButton)
                        .addGap(18, 18, 18)
                        .addComponent(redoButton))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addComponent(resizeButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        greyLayout.setVerticalGroup(
            greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(greyLayout.createSequentialGroup()
                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(greyLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(greyLayout.createSequentialGroup()
                                .addComponent(colorButton, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))
                            .addGroup(greyLayout.createSequentialGroup()
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(blue, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(red, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purple, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton15, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orange, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(pink, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(green, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labani, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yellow, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(black, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(thicknessSlider, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(logoLabel, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                            .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addGroup(greyLayout.createSequentialGroup()
                                    .addComponent(paintButton1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addGap(9, 9, 9)
                                    .addComponent(eraseButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13))
                                .addComponent(jSeparator3, GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, GroupLayout.Alignment.TRAILING)
                                .addGroup(greyLayout.createSequentialGroup()
                                    .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(redoButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(undoButton)
                                        .addComponent(moveButton, GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel17))
                                    .addGap(18, 18, 18)
                                    .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(screenshotButton, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(resizeButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clearButton, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(greyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(greyLayout.createSequentialGroup()
                        .addComponent(arcButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(greyLayout.createSequentialGroup()
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
                                .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addGroup(greyLayout.createSequentialGroup()
                                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(triangleButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lineSegmentButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel16))
                                        .addGap(19, 19, 19)
                                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(squareButton, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(circleButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rectangleButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator6, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
                                .addGroup(greyLayout.createSequentialGroup()
                                    .addComponent(copyButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pasteButton, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator5, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(greyLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel19))
                        .addGap(30, 30, 30))))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(grey, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPage1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grey, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPage1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButtonActionPerformed
        PaintBoard.currentMode =10;
    }//GEN-LAST:event_pasteButtonActionPerformed


    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        PaintBoard.currentMode =9;
    }//GEN-LAST:event_copyButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        PaintBoard.currentMode =8;
    }//GEN-LAST:event_moveButtonActionPerformed

    private void arcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcButtonActionPerformed
        PaintBoard.currentMode =11;

//        ShapeDecorator sd=new ShapeDecorator(shapes.get(i));        // TODO add your handling code here:
    }//GEN-LAST:event_arcButtonActionPerformed

    private void thicknessSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thicknessSliderMouseReleased
        PaintBoard.currentStroke = thicknessSlider.getValue();
    }//GEN-LAST:event_thicknessSliderMouseReleased

    private void thicknessSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thicknessSliderMouseClicked
        PaintBoard.currentStroke = thicknessSlider.getValue();
    }//GEN-LAST:event_thicknessSliderMouseClicked

    private void thicknessSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thicknessSliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_thicknessSliderStateChanged

    private void logoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoLabelMouseClicked
        PaintBoard.done.clear();
        PaintBoard.redo.clear();
        PaintBoard.shapes.clear();
        PaintBoard.currentMode = 5;
        this.setVisible(false);
        new StartPage().setVisible(true);
    }//GEN-LAST:event_logoLabelMouseClicked

    private void paintButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintButton1ActionPerformed
        PaintBoard.currentMode = 5;
    }//GEN-LAST:event_paintButton1ActionPerformed

    private void eraseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseButtonActionPerformed
        PaintBoard.currentMode = 6;
    }//GEN-LAST:event_eraseButtonActionPerformed

    private void screenshotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenshotButtonActionPerformed
    Screenshotter screenshoter = Screenshotter.createScreenshotter();
    screenshoter.screenShot();
                JOptionPane.showMessageDialog(null, "Screenshot saved!", "Screenshot", JOptionPane.INFORMATION_MESSAGE);

//        Screenshotter.screenShot();
    }//GEN-LAST:event_screenshotButtonActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        PaintBoard.currentColor = Color.GRAY;
        colorButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowActionPerformed
        PaintBoard.currentColor = Color.YELLOW;        // TODO add your handling code here:
        colorButton.setBackground(Color.YELLOW);
    }//GEN-LAST:event_yellowActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        PaintBoard.currentColor = Color.GREEN;
        colorButton.setBackground(Color.GREEN);
    }//GEN-LAST:event_greenActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        PaintBoard.currentColor = Color.RED;
        colorButton.setBackground(Color.RED);
    }//GEN-LAST:event_redActionPerformed

    private void blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueActionPerformed
        PaintBoard.currentColor = Color.BLUE;
        colorButton.setBackground(Color.BLUE);
    }//GEN-LAST:event_blueActionPerformed

    private void blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackActionPerformed
        PaintBoard.currentColor = Color.BLACK;
        colorButton.setBackground(Color.BLACK);
    }//GEN-LAST:event_blackActionPerformed

    private void purpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleActionPerformed
        PaintBoard.currentColor = Color.MAGENTA;
        colorButton.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_purpleActionPerformed

    private void labaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labaniActionPerformed
        PaintBoard.currentColor = Color.CYAN;
        colorButton.setBackground(Color.CYAN);
    }//GEN-LAST:event_labaniActionPerformed

    private void pinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkActionPerformed
        PaintBoard.currentColor = Color.pink;
        colorButton.setBackground(Color.pink);
    }//GEN-LAST:event_pinkActionPerformed

    private void orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActionPerformed
        PaintBoard.currentColor = Color.ORANGE;
        colorButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_orangeActionPerformed

    private void resizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeButtonActionPerformed
        PaintBoard.currentMode = 7;
    }//GEN-LAST:event_resizeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        ClearedScreen.clearScreen();
        repaint();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoButtonActionPerformed
        try{
        GeometricShape topShape = PaintBoard.redo.pop();
        GeometricShape prev = topShape.getPreviousShape();
        PaintBoard.done.add(topShape);
        if(prev == null) {
            PaintBoard.shapes.add(topShape);
        }
        else{
            PaintBoard.shapes.remove(prev);
            PaintBoard.shapes.add(topShape);
        }
        repaint();
    }catch (Exception e){
        //
    }


    }//GEN-LAST:event_redoButtonActionPerformed

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        Color tempColor = JColorChooser.showDialog(null, "Paint Color", Color.black);
        if (tempColor != null) {
            PaintBoard.currentColor = tempColor;
            colorButton.setBackground(tempColor);
        }
    }//GEN-LAST:event_colorButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed

        try{
            GeometricShape topShape = PaintBoard.done.pop();
            GeometricShape prev = topShape.getPreviousShape();
            PaintBoard.redo.add(topShape);

            if(prev == null) {
                PaintBoard.shapes.remove(topShape);
            }
            else{
                PaintBoard.shapes.remove(topShape);
                PaintBoard.shapes.add(prev);
            }
        } catch(Exception ex){
            //
        }
        repaint();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void triangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleButtonActionPerformed
        PaintBoard.currentMode = 3;
    }//GEN-LAST:event_triangleButtonActionPerformed

    private void rectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleButtonActionPerformed
        PaintBoard.currentMode = 1;
    }//GEN-LAST:event_rectangleButtonActionPerformed

    private void squareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareButtonActionPerformed
        PaintBoard.currentMode = 2;
    }//GEN-LAST:event_squareButtonActionPerformed

    private void lineSegmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSegmentButtonActionPerformed
        PaintBoard.currentMode = 0;
    }//GEN-LAST:event_lineSegmentButtonActionPerformed

    private void circleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleButtonActionPerformed
        PaintBoard.currentMode = 4;
    }//GEN-LAST:event_circleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Paint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton arcButton;
    private JButton black;
    private JButton blue;
    private JButton circleButton;
    private JButton clearButton;
    private JButton colorButton;
    private JButton copyButton;
    private JButton eraseButton;
    private JButton green;
    private JPanel grey;
    private JButton jButton15;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JSeparator jSeparator4;
    private JSeparator jSeparator5;
    private JSeparator jSeparator6;
    private JButton labani;
    private JButton lineSegmentButton;
    private JLabel logoLabel;
    private JButton moveButton;
    private JButton orange;
    private JButton paintButton1;
    private JButton pasteButton;
    private JButton pink;
    private JButton purple;
    private JButton rectangleButton;
    private JButton red;
    private JButton redoButton;
    private JButton resizeButton;
    private JButton screenshotButton;
    private JButton squareButton;
    private JSlider thicknessSlider;
    private JButton triangleButton;
    private JButton undoButton;
    private PaintBoard viewPage1;
    private JButton yellow;
    // End of variables declaration//GEN-END:variables
}
